version: 0.2

phases:
  pre_build:
    commands:
      - echo "Install dependencies"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Run unit tests"
      - python -m unittest discover tests