version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Flask app...
      - python app.py

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running unit tests...
      - python -m unittest test_app.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes